repo_name: VeritasIA
site_name: VeritasIA
repo_url: https://github.com/unb-mds/2026-2-VeritasIA
site_description: "Documentação oficial do VeritasIA"
docs_dir: docs

theme: 
  name: material
  logo: assets/texto.png
  favicon: assets/Logo.png
  custom_dir: overrides
  language: pt-BR
  features:
    - navigation.tabs
  palette:
    primary: custom
    accent: custom

nav:
  - Home: index.md
  - Arquitetura: projeto/Arquitetura.md
  - Requisitos: projeto/Requisitos.md
  - Organização:
      - Sprint 1: projeto/sprint1.md
      - Sprint 2: projeto/sprint2.md
      - Sprint 3: projeto/sprint3.md
      - Sprint 4: projeto/sprint4.md
      - Sprint 5: projeto/sprint5.md
      - Sprint 6: projeto/sprint6.md
      - Sprint 7: projeto/sprint7.md
      - Sprint 8: projeto/sprint8.md
      - Sprint 9: projeto/sprint9.md
      - Sprint 10: projeto/sprint10.md
  - Frontend:
      - React: frontend/React.md
      - Prototipagem: frontend/Prototipagem.md
  - Backend:
      - FastAPI: backend/FastAPI/FastAPI.md
      - Main: backend/FastAPI/base/main.md
      - Banco de Dados: backend/FastAPI/banco de dados/database.md
      - Models: backend/FastAPI/banco de dados/models.md
      - Adapters: backend/FastAPI/adapters/adapter.md
      - Schemas: backend/FastAPI/schemas/schemas.md
      - Web Scraping: backend/scrapy/scrapy.md
      - Workflow Scrapy: backend/scrapy/Automacao.md
      - LangChain: backend/langChain/LangChain.md
      - Controlador: backend/langChain/LangChainControlador.md
      - WorkFlow LangChain: backend/langChain/LangChainWorkFlow.md

  - Participantes:
        - sobre-nos.md

  - DashBoard:
      - Produtividade: dashboard/dashboard.md

site_dir: site

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          import:
            - https://docs.python.org/3/objects.inv