site_name: VeritasIA 
site_description: "Documentação oficial do VeritasIA"

theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  custom_dir: overrides
  language: pt-BR

  palette:
    primary: custom
    accent: custom

nav:
  - Home: 
      - Sobre o Projeto: index.md
      - Sobre Nós: sobrenos.md

  - Projeto:
      - Product Backlog: projeto/product_backlog.md
      - Requisitos: projeto/Requisitos.md
      - Sprint 1: projeto/sprint1.md
      - Sprint 2: projeto/sprint2.md
      - Sprint 3: projeto/sprint3.md
      - Equipe: sobrenos.md
    
  - Frontend:
      - React: frontend/React.md
      - Prototipagem: frontend/Prototipagem.md

  - Backend:
      - FastAPI: backend/FastAPI.md
      - Web Scraping: backend/Scrapy.md
      - LangChain: backend/LangChain.md

  - DashBoard:
      - Produtividade: dashboard/index.html

docs_dir: docs
site_dir: site

extra_css:
  - stylesheets/extra.css

plugins:
  - search